default_notification_src_address: ""
default_notification_to_address: ""
git:
    detect_rename: false
github:
    token: ""
    organization_name: ""
notifications: false
repo_groups: {}
rules_to_groups: {}
skip_repo_list: []
smtp:
    host: ""
    port: 0
    username: ""
    password: ""
    use_tls: true
subscribers: {}
